phases:
  install:
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - aws configure set default.region $AWS_REGION
      - chmod 755 scripts/*.sh

  build:
    commands:
      - pycodestyle squrl
      - pydocstyle squrl
      - pytest

  post_build:
    commands:
      - scripts/deploy.sh
