version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install aws-sam-cli tox

  pre_build:
    commands:
      - aws configure set default.region $AWS_REGION
      - chmod 755 scripts/*.sh

  build:
    commands:
      - tox

  post_build:
    commands:
      - scripts/deploy.sh
