AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Squrl SAM Template

Globals:
  Function:
    Timeout: 3

Parameters:
  ApiVersionParameter:
    Description: The Api deployment stage and lambda alias
    Type: String
    Default: v1

  S3BucketParameter:
    Description: S3 Bucket
    Type: String
    Default: www.squrl.com

Resources:
  SqurlApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiVersionParameter

  SqurlApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref ApiVersionParameter
      Handler: lambda_function.handler
      Runtime: python3.7
      CodeUri: squrl
      Policies:
       - S3CrudPolicy:
            BucketName: !Ref S3BucketParameter

      Environment:
        Variables:
          S3_BUCKET: !Ref S3BucketParameter
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref SqurlApi
            Method: get
            Path: /url
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref SqurlApi
            Method: post
            Path: /url

Outputs:
  SqurlApi:
    Description: Api Gateway Endpoint Url
    Value: !Sub https://${SqurlApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiVersionParameter}/

  SqurlApiLambda:
    Description: Squrl Lambda Function Arn
    Value: !GetAtt SqurlApiLambda.Arn

  SqurlApiLambdaIamRole:
    Description: Squrl Lambda Execution Role Arn
    Value: !GetAtt SqurlApiLambdaRole.Arn
